name: 'Repository Dispatch'
description: 'Create a repository dispatch event'

inputs:
  client-payload:
    description: 'The payload to send with the event'
    required: true
    default: '{}'
runs:
  using: 'node20'
  main: 'src/index.ts'
branding:
  icon: 'target'
  color: 'gray-dark'