name: Repository Dispatch
on:
  repository_dispatch:
    types: [workflow_dispatch]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Dump the client payload context
        if: github.event.client_payload
        env:
          PAYLOAD_CONTEXT: ${{ toJson([github.event.client_payload]) }}
        run: echo "$PAYLOAD_CONTEXT"
        
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Test"
        run: |
          touch .env
          rm .env
          touch .env
          echo PAYLOAD_CONTEXT=${{ env.PAYLOAD_CONTEXT }} >> .env
          yarn install && yarn test