name: Call Another Workflow

on:
  push:
    branches:
      - master

jobs:
  call:
    runs-on: ubuntu-latest
    steps:
      - name: Call Repo B Workflow
        uses: actions-github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const reponse = await github.actions.createWorkflowDispatch({
              owner: 'caiofaabio',
              repo: 'caiofaabio/repoB',
              workflow_id: 'main.yml',
              ref: 'main',
              inputs: {
                parameter_name: 'parameter_value'
              }
            })
            console.log(response)