name: Main test

on:
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: main
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Test"
        run: touch .env
          && rm .env
          && touch .env
          && echo WORKSPACE=${{ secrets.WORKSPACE }} >> .env
          && yarn install && yarn test
