name: Repository Dispatch

on:
  repository_dispatch:
    types: [my-event]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      # - name: "Dump the client payload context"
      #   env: 
      #     CLIENT_CONTEXT: ${{ toJson(github.event.client-payload) }}
      #   run: echo $CLIENT_CONTEXT
      
      # - name: Checkout Repo
      #   uses: actions/checkout@v4

      # - name: "Setup Node.js environment"
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: '20'

      # - name: Install dependencies
      #   run: yarn install 

      # - name: Build
      #   run: yarn build