name: Call Another Workflow

on:
  push:
    branches:
      - master

jobs:
  call:
    runs-on: ubuntu-latest
    steps:
      - name: Call Repo B Workflow
        uses: octokit/request-action@v2
        with:
          route: POST /repos/caiofaabio/repoB/actions/workflows/main.yml/dispatches
          token: ${{ secrets.TOKEN_TEST_CLASSIC }}
          ref: main
          inputs: |
            parameter_name=parameter_value
    # steps:
    #   - name: Call Repo B Workflow
    #     uses: actions-github-script@v5
    #     with:
    #       github-token: ${{ secrets.TOKEN_TEST_CLASSIC }}
    #       script: |
    #         const response = await github.actions.createWorkflowDispatch({
    #           owner: 'caiofaabio',
    #           repo: 'repoB',
    #           workflow_id: 'main.yml',
    #           ref: 'main',
    #           inputs: {
    #             parameter_name: 'parameter_value'
    #           }
    #         })
    #         console.log(response)