name: Call Another Workflow

on:
  push:
    branches:
      - main

jobs:
  call:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repo
        uses: actions/checkout@v2
     
      - name: Hello World CaioFabio
        uses: caiofaabio/repoB@0.1

        with:
          helloWord: ''
          timestamp: true
          
      
      # - name: Print timestamp
      #   run: echo ${{ steps.timestamp.outputs.timestamp }}