name: Call Another Workflow

on:
  push:
    branches:
      - master

jobs:
  call:
    runs-on: ubuntu-latest
    steps:
      - name: Call Repo B Workflow
        uses: octokit/request-action@v2
        with:
          route: POST /repos/:owner/:repo/actions/workflows/:workflow_id/dispatches
          owner: caiofaabio
          repo: repoB
          workflow_id: main.yml
          ref: main
          inputs: |
            parameter_name=parameter_value
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_TEST_CLASSIC }}